// Generated by gencpp from file hmm_sim/classifier_output.msg
// DO NOT EDIT!


#ifndef HMM_SIM_MESSAGE_CLASSIFIER_OUTPUT_H
#define HMM_SIM_MESSAGE_CLASSIFIER_OUTPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace hmm_sim
{
template <class ContainerAllocator>
struct classifier_output_
{
  typedef classifier_output_<ContainerAllocator> Type;

  classifier_output_()
    : pp_output()  {
    }
  classifier_output_(const ContainerAllocator& _alloc)
    : pp_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _pp_output_type;
  _pp_output_type pp_output;





  typedef boost::shared_ptr< ::hmm_sim::classifier_output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hmm_sim::classifier_output_<ContainerAllocator> const> ConstPtr;

}; // struct classifier_output_

typedef ::hmm_sim::classifier_output_<std::allocator<void> > classifier_output;

typedef boost::shared_ptr< ::hmm_sim::classifier_output > classifier_outputPtr;
typedef boost::shared_ptr< ::hmm_sim::classifier_output const> classifier_outputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hmm_sim::classifier_output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hmm_sim::classifier_output_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hmm_sim::classifier_output_<ContainerAllocator1> & lhs, const ::hmm_sim::classifier_output_<ContainerAllocator2> & rhs)
{
  return lhs.pp_output == rhs.pp_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hmm_sim::classifier_output_<ContainerAllocator1> & lhs, const ::hmm_sim::classifier_output_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hmm_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hmm_sim::classifier_output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hmm_sim::classifier_output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hmm_sim::classifier_output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hmm_sim::classifier_output_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmm_sim::classifier_output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmm_sim::classifier_output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hmm_sim::classifier_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e1c1a87e35ecc5a2d359b86d7f3c216";
  }

  static const char* value(const ::hmm_sim::classifier_output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e1c1a87e35ecc5aULL;
  static const uint64_t static_value2 = 0x2d359b86d7f3c216ULL;
};

template<class ContainerAllocator>
struct DataType< ::hmm_sim::classifier_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hmm_sim/classifier_output";
  }

  static const char* value(const ::hmm_sim::classifier_output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hmm_sim::classifier_output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray pp_output\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::hmm_sim::classifier_output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hmm_sim::classifier_output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pp_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct classifier_output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hmm_sim::classifier_output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hmm_sim::classifier_output_<ContainerAllocator>& v)
  {
    s << indent << "pp_output: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.pp_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HMM_SIM_MESSAGE_CLASSIFIER_OUTPUT_H
