// Generated by gencpp from file rosneuro_msgs/GetAcquisitionInfoRequest.msg
// DO NOT EDIT!


#ifndef ROSNEURO_MSGS_MESSAGE_GETACQUISITIONINFOREQUEST_H
#define ROSNEURO_MSGS_MESSAGE_GETACQUISITIONINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosneuro_msgs
{
template <class ContainerAllocator>
struct GetAcquisitionInfoRequest_
{
  typedef GetAcquisitionInfoRequest_<ContainerAllocator> Type;

  GetAcquisitionInfoRequest_()
    {
    }
  GetAcquisitionInfoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAcquisitionInfoRequest_

typedef ::rosneuro_msgs::GetAcquisitionInfoRequest_<std::allocator<void> > GetAcquisitionInfoRequest;

typedef boost::shared_ptr< ::rosneuro_msgs::GetAcquisitionInfoRequest > GetAcquisitionInfoRequestPtr;
typedef boost::shared_ptr< ::rosneuro_msgs::GetAcquisitionInfoRequest const> GetAcquisitionInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rosneuro_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosneuro_msgs/GetAcquisitionInfoRequest";
  }

  static const char* value(const ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAcquisitionInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rosneuro_msgs::GetAcquisitionInfoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSNEURO_MSGS_MESSAGE_GETACQUISITIONINFOREQUEST_H
