// Generated by gencpp from file rosneuro_msgs/NeuroFrame.msg
// DO NOT EDIT!


#ifndef ROSNEURO_MSGS_MESSAGE_NEUROFRAME_H
#define ROSNEURO_MSGS_MESSAGE_NEUROFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rosneuro_msgs/NeuroHeader.h>
#include <rosneuro_msgs/NeuroDataFloat.h>
#include <rosneuro_msgs/NeuroDataFloat.h>
#include <rosneuro_msgs/NeuroDataInt32.h>

namespace rosneuro_msgs
{
template <class ContainerAllocator>
struct NeuroFrame_
{
  typedef NeuroFrame_<ContainerAllocator> Type;

  NeuroFrame_()
    : header()
    , neuroheader()
    , sr(0)
    , eeg()
    , exg()
    , tri()  {
    }
  NeuroFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , neuroheader(_alloc)
    , sr(0)
    , eeg(_alloc)
    , exg(_alloc)
    , tri(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::rosneuro_msgs::NeuroHeader_<ContainerAllocator>  _neuroheader_type;
  _neuroheader_type neuroheader;

   typedef uint16_t _sr_type;
  _sr_type sr;

   typedef  ::rosneuro_msgs::NeuroDataFloat_<ContainerAllocator>  _eeg_type;
  _eeg_type eeg;

   typedef  ::rosneuro_msgs::NeuroDataFloat_<ContainerAllocator>  _exg_type;
  _exg_type exg;

   typedef  ::rosneuro_msgs::NeuroDataInt32_<ContainerAllocator>  _tri_type;
  _tri_type tri;





  typedef boost::shared_ptr< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> const> ConstPtr;

}; // struct NeuroFrame_

typedef ::rosneuro_msgs::NeuroFrame_<std::allocator<void> > NeuroFrame;

typedef boost::shared_ptr< ::rosneuro_msgs::NeuroFrame > NeuroFramePtr;
typedef boost::shared_ptr< ::rosneuro_msgs::NeuroFrame const> NeuroFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator1> & lhs, const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.neuroheader == rhs.neuroheader &&
    lhs.sr == rhs.sr &&
    lhs.eeg == rhs.eeg &&
    lhs.exg == rhs.exg &&
    lhs.tri == rhs.tri;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator1> & lhs, const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosneuro_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "797997e5036eb017437ce855856d3bad";
  }

  static const char* value(const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x797997e5036eb017ULL;
  static const uint64_t static_value2 = 0x437ce855856d3badULL;
};

template<class ContainerAllocator>
struct DataType< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosneuro_msgs/NeuroFrame";
  }

  static const char* value(const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NeuroFrame Message\n"
"\n"
"# Header\n"
"Header header\n"
"\n"
"# NeuroHeader\n"
"NeuroHeader neuroheader\n"
"\n"
"# Sampling rate\n"
"uint16 sr\n"
"\n"
"# NeuroData\n"
"NeuroDataFloat eeg\n"
"NeuroDataFloat exg\n"
"NeuroDataInt32 tri\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rosneuro_msgs/NeuroHeader\n"
"uint32 seq\n"
"\n"
"================================================================================\n"
"MSG: rosneuro_msgs/NeuroDataFloat\n"
"NeuroDataInfo info\n"
"float32[] data\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rosneuro_msgs/NeuroDataInfo\n"
"# NeuroDataInfo Message\n"
"\n"
"uint16    nsamples\n"
"uint16    nchannels\n"
"uint16    stride\n"
"string    unit\n"
"string    transducter\n"
"string    prefiltering		# Hardware prefiltering\n"
"uint8     isint\n"
"float64[] minmax\n"
"string[]  labels				# Labels of channels\n"
"\n"
"================================================================================\n"
"MSG: rosneuro_msgs/NeuroDataInt32\n"
"NeuroDataInfo info\n"
"int32[] data\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.neuroheader);
      stream.next(m.sr);
      stream.next(m.eeg);
      stream.next(m.exg);
      stream.next(m.tri);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeuroFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosneuro_msgs::NeuroFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosneuro_msgs::NeuroFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "neuroheader: ";
    s << std::endl;
    Printer< ::rosneuro_msgs::NeuroHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.neuroheader);
    s << indent << "sr: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sr);
    s << indent << "eeg: ";
    s << std::endl;
    Printer< ::rosneuro_msgs::NeuroDataFloat_<ContainerAllocator> >::stream(s, indent + "  ", v.eeg);
    s << indent << "exg: ";
    s << std::endl;
    Printer< ::rosneuro_msgs::NeuroDataFloat_<ContainerAllocator> >::stream(s, indent + "  ", v.exg);
    s << indent << "tri: ";
    s << std::endl;
    Printer< ::rosneuro_msgs::NeuroDataInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.tri);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSNEURO_MSGS_MESSAGE_NEUROFRAME_H
