(cl:defpackage rosneuro_msgs-srv
  (:use )
  (:export
   "GETACQUISITIONINFO"
   "<GETACQUISITIONINFO-REQUEST>"
   "GETACQUISITIONINFO-REQUEST"
   "<GETACQUISITIONINFO-RESPONSE>"
   "GETACQUISITIONINFO-RESPONSE"
  ))

