# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosneuro_msgs/GetAcquisitionInfoRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetAcquisitionInfoRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "rosneuro_msgs/GetAcquisitionInfoRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetAcquisitionInfoRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosneuro_msgs/GetAcquisitionInfoResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rosneuro_msgs.msg
import std_msgs.msg

class GetAcquisitionInfoResponse(genpy.Message):
  _md5sum = "8cf1aae8f1ae02fdc8775b1362badac5"
  _type = "rosneuro_msgs/GetAcquisitionInfoResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool            result

string device_model
string device_id

NeuroFrame frame


================================================================================
MSG: rosneuro_msgs/NeuroFrame
# NeuroFrame Message

# Header
Header header

# NeuroHeader
NeuroHeader neuroheader

# Sampling rate
uint16 sr

# NeuroData
NeuroDataFloat eeg
NeuroDataFloat exg
NeuroDataInt32 tri




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: rosneuro_msgs/NeuroHeader
uint32 seq

================================================================================
MSG: rosneuro_msgs/NeuroDataFloat
NeuroDataInfo info
float32[] data



================================================================================
MSG: rosneuro_msgs/NeuroDataInfo
# NeuroDataInfo Message

uint16    nsamples
uint16    nchannels
uint16    stride
string    unit
string    transducter
string    prefiltering		# Hardware prefiltering
uint8     isint
float64[] minmax
string[]  labels				# Labels of channels

================================================================================
MSG: rosneuro_msgs/NeuroDataInt32
NeuroDataInfo info
int32[] data


"""
  __slots__ = ['result','device_model','device_id','frame']
  _slot_types = ['bool','string','string','rosneuro_msgs/NeuroFrame']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result,device_model,device_id,frame

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetAcquisitionInfoResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = False
      if self.device_model is None:
        self.device_model = ''
      if self.device_id is None:
        self.device_id = ''
      if self.frame is None:
        self.frame = rosneuro_msgs.msg.NeuroFrame()
    else:
      self.result = False
      self.device_model = ''
      self.device_id = ''
      self.frame = rosneuro_msgs.msg.NeuroFrame()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.result
      buff.write(_get_struct_B().pack(_x))
      _x = self.device_model
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.device_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.frame.header.seq, _x.frame.header.stamp.secs, _x.frame.header.stamp.nsecs))
      _x = self.frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I4H().pack(_x.frame.neuroheader.seq, _x.frame.sr, _x.frame.eeg.info.nsamples, _x.frame.eeg.info.nchannels, _x.frame.eeg.info.stride))
      _x = self.frame.eeg.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.eeg.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.eeg.info.minmax))
      length = len(self.frame.eeg.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.eeg.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.eeg.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.eeg.data))
      _x = self
      buff.write(_get_struct_3H().pack(_x.frame.exg.info.nsamples, _x.frame.exg.info.nchannels, _x.frame.exg.info.stride))
      _x = self.frame.exg.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.exg.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.exg.info.minmax))
      length = len(self.frame.exg.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.exg.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.exg.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.exg.data))
      _x = self
      buff.write(_get_struct_3H().pack(_x.frame.tri.info.nsamples, _x.frame.tri.info.nchannels, _x.frame.tri.info.stride))
      _x = self.frame.tri.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.tri.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.tri.info.minmax))
      length = len(self.frame.tri.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.tri.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.tri.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.frame.tri.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.frame is None:
        self.frame = rosneuro_msgs.msg.NeuroFrame()
      end = 0
      start = end
      end += 1
      (self.result,) = _get_struct_B().unpack(str[start:end])
      self.result = bool(self.result)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.device_model = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.device_model = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.device_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.device_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.frame.header.seq, _x.frame.header.stamp.secs, _x.frame.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.frame.neuroheader.seq, _x.frame.sr, _x.frame.eeg.info.nsamples, _x.frame.eeg.info.nchannels, _x.frame.eeg.info.stride,) = _get_struct_I4H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.eeg.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.eeg.info.minmax = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.eeg.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.eeg.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.eeg.data = s.unpack(str[start:end])
      _x = self
      start = end
      end += 6
      (_x.frame.exg.info.nsamples, _x.frame.exg.info.nchannels, _x.frame.exg.info.stride,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.exg.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.exg.info.minmax = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.exg.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.exg.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.exg.data = s.unpack(str[start:end])
      _x = self
      start = end
      end += 6
      (_x.frame.tri.info.nsamples, _x.frame.tri.info.nchannels, _x.frame.tri.info.stride,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.tri.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.tri.info.minmax = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.tri.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.tri.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.tri.data = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.result
      buff.write(_get_struct_B().pack(_x))
      _x = self.device_model
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.device_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.frame.header.seq, _x.frame.header.stamp.secs, _x.frame.header.stamp.nsecs))
      _x = self.frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I4H().pack(_x.frame.neuroheader.seq, _x.frame.sr, _x.frame.eeg.info.nsamples, _x.frame.eeg.info.nchannels, _x.frame.eeg.info.stride))
      _x = self.frame.eeg.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.eeg.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.eeg.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.frame.eeg.info.minmax.tostring())
      length = len(self.frame.eeg.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.eeg.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.eeg.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.frame.eeg.data.tostring())
      _x = self
      buff.write(_get_struct_3H().pack(_x.frame.exg.info.nsamples, _x.frame.exg.info.nchannels, _x.frame.exg.info.stride))
      _x = self.frame.exg.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.exg.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.exg.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.frame.exg.info.minmax.tostring())
      length = len(self.frame.exg.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.exg.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.exg.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.frame.exg.data.tostring())
      _x = self
      buff.write(_get_struct_3H().pack(_x.frame.tri.info.nsamples, _x.frame.tri.info.nchannels, _x.frame.tri.info.stride))
      _x = self.frame.tri.info.unit
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.transducter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.prefiltering
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.frame.tri.info.isint
      buff.write(_get_struct_B().pack(_x))
      length = len(self.frame.tri.info.minmax)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.frame.tri.info.minmax.tostring())
      length = len(self.frame.tri.info.labels)
      buff.write(_struct_I.pack(length))
      for val1 in self.frame.tri.info.labels:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      length = len(self.frame.tri.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.frame.tri.data.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.frame is None:
        self.frame = rosneuro_msgs.msg.NeuroFrame()
      end = 0
      start = end
      end += 1
      (self.result,) = _get_struct_B().unpack(str[start:end])
      self.result = bool(self.result)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.device_model = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.device_model = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.device_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.device_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.frame.header.seq, _x.frame.header.stamp.secs, _x.frame.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.frame.neuroheader.seq, _x.frame.sr, _x.frame.eeg.info.nsamples, _x.frame.eeg.info.nchannels, _x.frame.eeg.info.stride,) = _get_struct_I4H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.eeg.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.eeg.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.eeg.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.eeg.info.minmax = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.eeg.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.eeg.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.eeg.data = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 6
      (_x.frame.exg.info.nsamples, _x.frame.exg.info.nchannels, _x.frame.exg.info.stride,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.exg.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.exg.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.exg.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.exg.info.minmax = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.exg.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.exg.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.exg.data = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 6
      (_x.frame.tri.info.nsamples, _x.frame.tri.info.nchannels, _x.frame.tri.info.stride,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.unit = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.unit = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.transducter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.transducter = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame.tri.info.prefiltering = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.frame.tri.info.prefiltering = str[start:end]
      start = end
      end += 1
      (self.frame.tri.info.isint,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.tri.info.minmax = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frame.tri.info.labels = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.frame.tri.info.labels.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame.tri.data = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3H = None
def _get_struct_3H():
    global _struct_3H
    if _struct_3H is None:
        _struct_3H = struct.Struct("<3H")
    return _struct_3H
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_I4H = None
def _get_struct_I4H():
    global _struct_I4H
    if _struct_I4H is None:
        _struct_I4H = struct.Struct("<I4H")
    return _struct_I4H
class GetAcquisitionInfo(object):
  _type          = 'rosneuro_msgs/GetAcquisitionInfo'
  _md5sum = '8cf1aae8f1ae02fdc8775b1362badac5'
  _request_class  = GetAcquisitionInfoRequest
  _response_class = GetAcquisitionInfoResponse
